#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \


# some more ls aliases
alias ll='exa -alF || ls -alF'
alias la='exa -A || ls -A'
alias ls='exa || ls'
alias l='ls -CF'

#general aliases
alias v="nvim"
alias vcf="nvim ~/.config/nvim/init.vim"
alias e="emacsclient $1 || emacs --daemon && emacsclient $1"

# vimwiki stufff
alias vw="nvim ~/vimwiki/index.wiki"
alias rendervw="nvim ~/vimwiki/index.wiki -c :VimwikiAll2HTML -c ':q'"
alias k="nvim ~/vimwiki/Knowledge\ base.wiki"

#directory shortcuts
alias vsm="cd /mnt/c/Users/Clark/vscodemain"
alias ..="cd .."

#some cargo aliases :)
alias cn='cargo new'
alias cnl='cargo new --lib'
alias ci='cargo init'
alias cr='cargo run'
alias cb='cargo build'
alias ct='cargo test'
alias c='cargo clippy || cargo check'
alias cw="cargo watch -c --poll -x 'clippy'"
alias cwr="cargo watch -c --poll -x run"
#-- -W clippy::pedantic
alias cbr='cargo build --release'
alias crr='cargo run --release'
alias crd="cargo rustdoc"
alias cft="cargo fmt"

#general rust aliases
alias rft='rustfmt'
alias rc='rustc'

#git aliases
alias g="git"
alias gcs="batcat -p -l bash /home/mehbark/main/misc/gitCliCheatSheet.js"
alias gco="git checkout"
alias gb="git branch"
alias gc="git commit -m"
alias gst="git status"
alias ga="git add"
alias gp="git push"
alias gl='git log --oneline --graph --decorate --all'
alias gi='git init'

#more complex aliases
alias ri="git init; cargo init"
alias rn="new_cargo_quick"
alias rnw="new_cargo_quick; cargo watch -c --poll -x clippy"

new_cargo_quick() {
  mkdir $1
  cd $1
  git init
  cargo init
}
